Normalizacja
coders-school/templates pull request #1
Opened 2020-08-22 21:21 UTC by MrMijagi

2020-08-24 09:55 UTC, Penthurion reviewed
Jak dla mnie wszystko w porządku. Nie mam żadnych sugestii.

2020-09-01 20:08 UTC, ziobron requested changes
Proszę o drobne poprawki w README.md

2020-09-01 20:08 UTC, ziobron commented on README.md
> +# Q&A sessions
```suggestion
# Szablony
```

2020-09-01 20:08 UTC, ziobron commented on README.md
> +### [Template specialization](module1/specialization.md)
Zmień na polski

2020-09-01 20:53 UTC, ziobron approved these changes

2020-09-01 20:53 UTC, merged