make_unique works
coders-school/templates pull request #12
Opened 2020-11-02 13:12 UTC by WojtekMs

2020-11-02 14:09 UTC, ziobron requested changes

2020-11-02 14:09 UTC, ziobron commented on module1/homework/make_unique/tests/tests.cpp
> +    auto uniqueRLC = cs::make_unique<MyType>(3, anotherValue, false);
ok, but how to check if perfect forwarding was used? Or in other words how to check if proper constructor was called?

2020-11-02 14:09 UTC, ziobron commented on module1/homework/make_unique/tests/tests.cpp
> +
I would like to see test for creating array with make unique.

2020-11-02 14:41 UTC, MaciejSalamonski approved these changes

2020-11-02 14:41 UTC, MaciejSalamonski commented on module1/homework/make_unique/make_unique.hpp
> +    template<typename ObjectType, typename... ArgTypes>
I think that sth is missing there. What about arrays?

2020-11-02 14:44 UTC, MaciejSalamonski approved these changes
:)

2020-11-02 14:44 UTC, MaciejSalamonski commented on module1/homework/make_unique/make_unique.hpp
> +{
I think that sth is missing there. What about arrays?

2020-11-03 09:18 UTC, WBigaj reviewed
I have checked your code and have nothing to add that was not mentioned by previous reviewers.

2020-11-03 11:22 UTC, ziobron requested changes

2020-11-03 11:22 UTC, ziobron commented on module1/homework/make_unique/make_unique.hpp
> +    std::enable_if_t<std::is_array_v<ArrayType>, std::unique_ptr<ArrayType>>
Good. There is also a bit simpler SFINAE with enable_if as additional template parameter instead of a return type.

2020-11-03 11:22 UTC, ziobron commented on module1/homework/make_unique/tests/tests.cpp
> +};
we want to avoid testing things with stdin/stdout. In this case it can be avoided.

2020-11-03 11:22 UTC, ziobron commented on module1/homework/make_unique/tests/tests.cpp
> +    EXPECT_EQ(expectedLRCOutput, actualLRCOutput);
there is an easier way. Each constructor should set different values for member fields. Then you can check if they were set properly.

2020-11-03 20:50 UTC, WojtekMs commented
As requested:
- make_unique for arrays is now changed to a simpler form with `std::enable_if_t` as additional template parameter
- perfect forwarding is tested without stdOut, constructors set member variables and their values are then checked

2020-11-03 21:26 UTC, ziobron approved these changes

2020-11-03 21:27 UTC, ziobron commented
{ "requirement_ids": [1119, 4443], "points": [3, 40] }

2020-11-03 21:27 UTC, closed without merging