Make_unique Homework
coders-school/templates pull request #13
Opened 2020-11-02 19:48 UTC by mateusz-talma

2020-11-02 20:54 UTC, majkel84 approved these changes

2020-11-02 22:30 UTC, MaciejSalamonski approved these changes
Good job :+1:

2020-11-03 09:20 UTC, WBigaj approved these changes
I have checked your code and it looks good 👍

2020-11-03 10:57 UTC, ziobron requested changes

2020-11-03 10:57 UTC, ziobron commented on module1/homework/make_unique/makeUnique-ut.cpp
> +        std::make_tuple(TestConsts::intValue, TestConsts::doubleValue));
std::tuple with std::make_tuple is redundant. std::make_tuple returns just std::tuple. Get rid of one of them.

2020-11-03 10:57 UTC, ziobron commented on module1/homework/make_unique/makeUnique-ut.cpp
> +                                                            TestConsts::boolValue));
It's still only one argument that is passed to make_unique and it is TestData. Please pass 3 arguments and create (not copy or move) TestData inside make_unique. So you have only cases when there is either 1 or 0 parameters passed. I need a proof in tests that your function can take any number of arguments :)
```suggestion
    auto ptr = myMakeUnique::make_unique<TestData>(TestConsts::intValue,
                                                   TestConsts::doubleValue,
                                                   TestConsts::boolValue);
```

2020-11-03 21:22 UTC, ziobron approved these changes

2020-11-03 21:22 UTC, ziobron commented
{ "requirement_ids": [1119, 4443], "points": [3, 40] }

2020-11-03 21:22 UTC, closed without merging