Homework make_unique
coders-school/templates pull request #6
Opened 2020-10-26 11:56 UTC by J-Cieplinski

2020-10-26 12:02 UTC, majkel84 approved these changes

2020-10-26 12:02 UTC, majkel84 commented on module1/homework/make_unique/make_unique.hpp
> +    template<typename T, typename... Args, typename = std::enable_if_t<!std::is_array_v<T>>>
good idea to pass enable_if as template argument

2020-10-26 13:35 UTC, MaciejSalamonski approved these changes
i dont have any comments. Good job 👍

2020-10-27 11:01 UTC, ziobron requested changes
Nice tests, but there is no valgrind / asan

2020-10-27 11:01 UTC, ziobron commented on .github/workflows/make_unique.yaml
> +        run: ctest -V
you do not check memory leaks with valgrind / asan

2020-10-27 11:01 UTC, ziobron commented on module1/homework/make_unique/make_unique.hpp
> +    }
This should be a proper implementation. Without that memory leaks / undefined behavior is possible.
```suggestion
    template<typename T>
    std::unique_ptr<T[]> make_unique(size_t size) {
        return std::unique_ptr<T[]>{new std::remove_extent_t<T>[size] {}};
    }
```

2020-10-27 11:01 UTC, ziobron commented on module1/homework/make_unique/test.cpp
> +    int d_ = testD;
implicit conversion. `testD` is `double`.

2020-10-27 11:01 UTC, ziobron commented on module1/homework/make_unique/test.cpp
> +}
Nice way of checking the behavior.
I rather thought about mock and checking if a proper method was called, but your method is very good 👍

2020-10-27 11:44 UTC, J-Cieplinski commented on .github/workflows/make_unique.yaml
> +        run: ctest -V
I saw no reason to add it. I'm using STL implementation of make_unique

2020-10-27 11:45 UTC, J-Cieplinski commented on module1/homework/make_unique/make_unique.hpp
> +    }
Oh, ok

2020-10-27 11:45 UTC, J-Cieplinski commented on module1/homework/make_unique/test.cpp
> +    int d_ = testD;
I messed up here, `d_` should be `double`

2020-10-27 11:51 UTC, J-Cieplinski commented on module1/homework/make_unique/make_unique.hpp
> +    }
However, this is not compiling :D And local valgrind without it showed no leaks

2020-10-27 12:43 UTC, ziobron approved these changes
Good. It looks that I incorrectly suggested replacing T with T[] in array version, because [] is already deduced by compiler and substituted with brackets.

2020-10-27 12:43 UTC, ziobron commented
{ "requirement_ids": [1119, 4443], "points": [3, 40] }

2020-10-27 12:43 UTC, closed without merging

2020-10-28 11:42 UTC, ziobron commented on .github/workflows/make_unique.yaml
> +        run: ctest -V
There is a reason. You used std::unique_ptr but it could be used incorrectly and cause memory leaks.